name: Deploy

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup variables
      id: vars
      run: echo "tag=${GITHUB_REF#refs/tags/releases/}" >> $GITHUB_OUTPUT

    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - run: echo $RELEASE_VERSION
    - run: echo $GITHUB_REF
